replicaCount: 1

image:
  tag: "25.2.0.102705-community"

edition: ""
community:
  enabled: true

service:
  type: LoadBalancer
  port: 9000

resources:
  limits:
    cpu: 500m
    memory: "1.5Gi"
    ephemeral-storage: 10000M
  requests:
    cpu: 100m
    memory: "1Gi"
    ephemeral-storage: 1536M  


persistence:
  enabled: true
  storageClass: "ebs-gp2"
  size: "4Gi"

postgresql:
  enabled: true
  postgresqlUsername: "sonarUser"
  postgresqlPassword: "sonarPass"
  postgresqlDatabase: "sonarDB"
  resources:
    limits:
      cpu: "100m"
      memory: "256Mi"
    requests:
      cpu: "50m"
      memory: "128Mi"
env:
  - name: SONAR_WEB_JAVAOPTS
    value: "-Xmx256m -Xms128m -XX:MaxMetaspaceSize=128m"
  - name: SONAR_CE_JAVAOPTS
    value: "-Xmx256m -Xms128m -XX:MaxMetaspaceSize=128m"
  - name: SONAR_SEARCH_JAVAOPTS
    value: "-Xmx512m -Xms512m -XX:MaxMetaspaceSize=128m"


#TODO - Change this to a secret
monitoringPasscode: "define_it"

#like here
# monitoringPasscodeSecretName: "sonar-monitoring-passcode"
# monitoringPasscodeSecretKey: "myStrongPasscode123"